// Generated by CoffeeScript 1.6.2
(function() {
  describe('Services', function() {
    var ctrl, mockCtrl, mockScope;

    mockCtrl = null;
    mockScope = null;
    ctrl = null;
    beforeEach(function() {
      ctrl = angular.module('tempModule', []).controller('DummyController', function($scope) {
        return console.log('DummyController init');
      });
      module('app');
      return module('tempModule');
    });
    beforeEach(inject(function($controller, $rootScope) {}));
    return describe('Dialog', function() {
      it('should instatiate the Dialog service', inject(function(Dialog) {
        return expect(Dialog).not.toBe(null);
      }));
      return it('should append/remove modal div to body', inject(function(Dialog) {
        var modalEl;

        modalEl = $('body').find('.modal');
        Dialog.show('partials/business_profile.jade', {
          controller: 'DummyController'
        }, {
          coupons: 'foo!'
        });
        expect($('body').find('.modal').length).toBe(1);
        Dialog.destroy();
        return expect($('body').find('.modal').length).toBe(0);
      }));
    });
  });

}).call(this);

/*
//@ sourceMappingURL=servicesSpec.map
*/
